apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonar-test
  name: sonar-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar-test
  strategy: {}
  template:
    metadata:
      labels:
        app: sonar-test
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: client
        image: busybox
        command:
          - "tail"
        args:
          - "-F"
          - "/dev/null"
      - image: postgres ## SHOULD BE A DEV OVERLAY
        name: potgres
        env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_USER
            value: user
      - image: simpleproject
        name: simpleproject
        envFrom:
        - configMapRef:
            name: simpleapp-configmap


