apiVersion: v1
kind: Service
metadata:
  labels:
    app: simpleapp
  name: sonar-test
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sonar-test
status:
  loadBalancer: {}
